### ISSUE TITLE
Face rig or expression warps faces

### ISSUE THREAD

**Issue by giulioriot** [animate1978/MB-Lab#304]
Using the face rig, or the face expression function, the model is badly distorted.

After the model is finalized, applying the face rig or face expression functions, the model warps instead of following the shape of the expression. 

![image](https://user-images.githubusercontent.com/7337834/95499922-47472c80-09a6-11eb-9c6f-2597deb6d35b.png)

![image](https://user-images.githubusercontent.com/7337834/95499954-55954880-09a6-11eb-81c7-63b3d6c3342a.png)
![image](https://user-images.githubusercontent.com/7337834/95500010-752c7100-09a6-11eb-88d7-7a24c2161b97.png)

**Comment by giulioriot** [comment]
![image](https://user-images.githubusercontent.com/7337834/95502242-d43fb500-09a9-11eb-828c-0c8be65608f5.png)

**Comment by giulioriot** [comment]
![image](https://user-images.githubusercontent.com/7337834/95505086-10751480-09ae-11eb-8e34-c3256d94691d.png)
I've just updated to last version but is the same

**Comment by giulioriot** [comment]
Got this error when I create face rig after updating to last version of MB-Lab

Traceback (most recent call last):
  File "C:\Users\giuli\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\__init__.py", line 2266, in execute
    rc = facerig.setup_face_rig(obj)
  File "C:\Users\giuli\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab\facerig.py", line 299, in setup_face_rig
    root_x, root_y, root_z, rc = get_root_bone_xyz_loc(obj)
ValueError: not enough values to unpack (expected 4, got 2)

location: <unknown location>:-1

**Comment by animate1978** [comment]
I see, this is not good, I will have to look into this...

**Comment by animate1978** [comment]
This could have been related to the fact that up until recently, the code was not updated for Blender 2.90+

I noticed from your screenshots that you are using a more recent build of Blender. You should try again using the 'master' branch of MB-Lab which has been fixed for the latest version of Blender.

Let me know how it performs

**Comment by animate1978** [comment]
Just a note : I used the latest version of MB-Lab... on Blender 2.82 and the FaceRig does not cause distortion. I should be getting an new GPU so I can run Blender 2.90+ so I will test this out then.

Also note that I did setup IK and Muscles as seen in the screenshots.

**Comment by giulioriot** [comment]
Ok Thank you so much!!!
So the version is still the 1.7.8 right?
I will try and let you know if it works,
Thank you again

**Comment by animate1978** [comment]
Yes this is still 1.7.8 but it has an internal version upgrade from x.x.x.42 to x.x.x.50

I still not sure what caused distortion like you have shown though, it's never been seen before and I cannot seem to replicate it either so more testing will be done.

**Comment by nameless667** [comment]
This distortion might have to do with random generator. I recall having the same issue after spamming "Generate" and then possibly undoing once and then applying a face rig.     On Tuesday, January 12, 2021, 07:09:06 PM GMT+2, animate1978 <notifications@github.com> wrote:  
 
 


Yes this is still 1.7.8 but it has an internal version upgrade from x.x.x.42 to x.x.x.50

I still not sure what caused distortion like you have shown though, it's never been seen before and I cannot seem to replicate it either so more testing will be done.
